# Generated by Django 2.2.5 on 2019-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('settings', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
