# Generated by Django 2.2.5 on 2019-11-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alerts',
            table='ALERTS',
        ),
    ]
