global_config = {'email': {'alert_interval': 300,
           'from_addr': 'slick.monitor.35@google.com',
           'password': 'VMware1!',
           'smtp_host': 'smtp.gmail.com',
           'smtp_port': 587,
           'ssl': True,
           'to_addr': 'akopbayev@vmware.com',
           'username': 'slick.monitor.35'},
 'syslog': {None}}
monitors = [{'hostname': 'google.com',
  'id': 0,
  'params': {'alert_type': 'email', 'count': 3, 'ftt': 3, 'interval': 15},
  'type': 'ping'},
 {'hostname': '4.4.4.4',
  'id': 1,
  'params': {'alert_type': 'email', 'count': 3, 'ftt': 3, 'interval': 15},
  'type': 'ping'},
 {'hostname': 'https://www.vmware.com',
  'id': 2,
  'params': {'alert_type': 'email', 'ftt': 1, 'interval': 10},
  'type': 'http'},
 {'hostname': 'bbc.com',
  'id': 3,
  'params': {'alert_type': 'email', 'ftt': 3, 'interval': 10},
  'type': 'http'}]
