# Generated by Django 2.2.5 on 2019-12-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('interval', models.IntegerField()),
                ('ftt', models.IntegerField()),
                ('alert_type', models.CharField(max_length=100)),
                ('alert_enabled', models.BooleanField()),
                ('params', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'MONITORS',
            },
        ),
    ]
