# Generated by Django 2.2.5 on 2019-12-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitors',
            unique_together={('hostname', 'type')},
        ),
    ]
