# Generated by Django 2.2.5 on 2019-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_auto_20191207_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitors',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
    ]
