# Generated by Django 2.2.5 on 2019-12-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_auto_20191207_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('monitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.Monitors', unique=True)),
            ],
            options={
                'db_table': 'STATES',
            },
        ),
    ]
