# Generated by Django 2.2.5 on 2019-12-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='monitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.Monitors'),
        ),
    ]
