# Generated by Django 2.2.5 on 2019-12-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_auto_20191212_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='States',
        ),
    ]
