# Generated by Django 2.2.5 on 2019-12-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_states'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STATES',
        ),
    ]
