# Generated by Django 2.2.5 on 2019-12-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0011_auto_20191212_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STATES',
        ),
    ]
