# Generated by Django 2.2.5 on 2019-12-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0015_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
